# -*- coding: utf-8 -*-
"""Copy of mutual_fund_plan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bouuDpe6hghtNUsMOTXOBuUCorsyc-5m

# Mutual Fund Plan with Python

## Importing libraries & Loading file
"""

import pandas as pd

data = pd.read_csv("/content/nifty50_closing_prices.csv") ## Local File location

print(data.head())

"""### Convert Date column to DateTime"""

data['Date'] = pd.to_datetime(data['Date'])

"""### Data Cleaning & EDA"""

print(data.isnull().sum())

"""## Stock Price Trends"""

import plotly.graph_objs as go
import plotly.express as px

fig = go.Figure()

for company in data.columns[1:]:
    fig.add_trace(go.Scatter(x=data['Date'], y=data[company],
                             mode='lines',
                             name=company,
                             opacity=0.5))

fig.update_layout(
    title='Stock Price Trends of All Indian Companies',
    xaxis_title='Date',
    yaxis_title='Closing Price (INR)',
    xaxis=dict(tickangle=45),
    legend=dict(
        x=1.05,
        y=1,
        traceorder="normal",
        font=dict(size=10),
        orientation="v"
    ),
    margin=dict(l=0, r=0, t=30, b=0),
    hovermode='x',
    template='plotly_white'
)

fig.show()

"""### Highest risk companies for Investing"""

all_companies = data.columns[1:]

volatility_all_companies = data[all_companies].std()

volatility_all_companies.sort_values(ascending=False).head(10)

"""### Highest growth rate for Investing"""

growth_all_companies = data[all_companies].pct_change() * 100

average_growth_all_companies = growth_all_companies.mean()

average_growth_all_companies.sort_values(ascending=False).head(10)

"""### Highest return on Investments"""

initial_prices_all = data[all_companies].iloc[0]
final_prices_all = data[all_companies].iloc[-1]

roi_all_companies = ((final_prices_all - initial_prices_all) / initial_prices_all) * 100

roi_all_companies.sort_values(ascending=False).head(10)

"""## Creating a Mutual Fund Plan Based on High ROI and Low Risk

To create a strategy for selecting companies with high ROI and low risk, we can use a combination of ROI and volatility (standard deviation) metrics. The goal is to find companies that offer a high return on investment (ROI) but with low volatility to minimize risk.

Here are the steps we can follow for creating a mutual fund plan:

1. Define ROI and Volatility Thresholds: We will set thresholds for ROI and volatility to select companies that provide good returns with lower risks.
2. Rank Companies by ROI and Volatility: Rank all companies based on their ROI and volatility scores.
3. Assign Investment Ratios: Allocate more investment to companies with higher ROI and lower volatility.

Let’s start by defining thresholds and selecting companies that meet the criteria of high ROI and low volatility:
"""

roi_threshold = roi_all_companies.median()
volatility_threshold = volatility_all_companies.median()

selected_companies = roi_all_companies[(roi_all_companies > roi_threshold) & (volatility_all_companies < volatility_threshold)]

selected_companies.sort_values(ascending=False)

"""To balance the investment between these companies, we can use an inverse volatility ratio for allocation. Companies with lower volatility will get a higher weight. Let’s calculate the weight for each company:"""

selected_volatility = volatility_all_companies[selected_companies.index]
inverse_volatility = 1 / selected_volatility

investment_ratios = inverse_volatility / inverse_volatility.sum()

investment_percentages = investment_ratios * 100
print(investment_percentages.sort_values(ascending=False))

"""# Analyzing Our Mutual Fund Plan

We have created a mutual fund plan for long-term investments. Now, let’s analyze and compare our mutual fund plan by comparing it with the high-performing companies in the stock market. Let’s start by comparing the risks in our mutual fund with the risk in the high growth companies:
"""

top_growth_companies = average_growth_all_companies.sort_values(ascending=False).head(10)
risk_growth_rate_companies = volatility_all_companies[top_growth_companies.index]
risk_mutual_fund_companies = volatility_all_companies[selected_companies.index]

fig = go.Figure()

fig.add_trace(go.Bar(
    y=risk_mutual_fund_companies.index,
    x=risk_mutual_fund_companies,
    orientation='h',  # Horizontal bar
    name='Mutual Fund Companies',
    marker=dict(color='blue')
))

fig.add_trace(go.Bar(
    y=risk_growth_rate_companies.index,
    x=risk_growth_rate_companies,
    orientation='h',
    name='Growth Rate Companies',
    marker=dict(color='green'),
    opacity=0.7
))

fig.update_layout(
    title='Risk Comparison: Mutual Fund vs Growth Rate Companies',
    xaxis_title='Volatility (Standard Deviation)',
    yaxis_title='Companies',
    barmode='overlay',
    legend=dict(title='Company Type'),
    template='plotly_white'
)

fig.show()

"""Now, let’s compare the ROI of both the groups as well:"""

expected_roi_mutual_fund = roi_all_companies[selected_companies.index]

expected_roi_growth_companies = roi_all_companies[top_growth_companies.index]

fig = go.Figure()

fig.add_trace(go.Bar(
    y=expected_roi_mutual_fund.index,
    x=expected_roi_mutual_fund,
    orientation='h',
    name='Mutual Fund Companies',
    marker=dict(color='blue')
))

fig.add_trace(go.Bar(
    y=expected_roi_growth_companies.index,
    x=expected_roi_growth_companies,
    orientation='h',
    name='Growth Rate Companies',
    marker=dict(color='green'),
    opacity=0.7
))

fig.update_layout(
    title='Expected ROI Comparison: Mutual Fund vs Growth Rate Companies',
    xaxis_title='Expected ROI (%)',
    yaxis_title='Companies',
    barmode='overlay',
    legend=dict(title='Company Type'),
    template='plotly_white'
)

fig.show()

"""The comparison between the risk (volatility) and expected ROI for mutual fund companies (in blue) and growth rate companies (in green) shows a clear trade-off. Mutual fund companies offer lower volatility, meaning they are less risky, but also provide lower expected returns. In contrast, growth rate companies demonstrate higher volatility, indicating more risk, but they offer much higher potential returns, especially companies like Bajaj Auto and Bajaj Finserv. This highlights a common investment dilemma: lower risk comes with a lower reward, while higher risk could yield higher returns.

For long-term investments, the goal is typically to find companies that offer a balance of stable returns and manageable risk. The companies in our mutual fund exhibit low volatility, meaning they are less risky, and their moderate returns make them solid choices for long-term, stable growth. They are well-suited for conservative investors who want steady returns without significant fluctuations in value.

# Calculating Expected Returns

Now, let’s calculate the expected returns a person will get from our mutual fund if he/she invests ₹5000 every month.

To calculate the expected value a person will accumulate over 1 year, 3 years, 5 years, and 10 years through the mutual fund plan, we can follow these steps:

1. Assume the person is investing 5000 rupees every month & increasing the investment amount by 10% every year.
2. Use the expected ROI from the mutual fund companies to simulate the growth over time.
3. Compute the compounded value of the investments for each period (1y, 3y, 5y, and 10y).
4. Visualize the accumulated value over these periods.
"""

import numpy as np
import plotly.graph_objects as go

# Parameters
initial_monthly_investment = 5000  # Starting monthly investment in INR
investment_years = [1, 3, 5, 10]   # Investment periods
n = 12  # Monthly compounding
annual_increase_rate = 0.10  # 10% increase in monthly investment every year

# Replace this with the actual ROI array or value
expected_roi_mutual_fund = np.array([12.5, 13.2, 14.0])  # Example ROI values
avg_roi = expected_roi_mutual_fund.mean() / 100  # Convert to decimal

# Function to calculate future value with increasing annual investments
def future_value_with_growth(initial_P, r, n, years, growth_rate):
    total_fv = 0
    for year in range(years):
        # Calculate monthly investment for this year
        P = initial_P * ((1 + growth_rate) ** year)
        # Time left for this annual investment to compound
        t = years - year
        # Future value of this year's monthly SIPs
        fv = P * (((1 + r / n) ** (n * t) - 1) / (r / n)) * (1 + r / n)
        total_fv += fv
    return total_fv

# Calculate future values for each investment period
future_values = [future_value_with_growth(initial_monthly_investment, avg_roi, n, t, annual_increase_rate)
                 for t in investment_years]

# Plotting
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[f"{year} year{'s' if year > 1 else ''}" for year in investment_years],
    y=future_values,
    mode='lines+markers',
    line=dict(color='blue'),
    marker=dict(size=8),
    name='Future Value'
))

fig.update_layout(
    title="Expected Value of Monthly SIP with 10% Annual Increase (₹5000 Starting)",
    xaxis_title="Investment Period",
    yaxis_title="Future Value (INR)",
    xaxis=dict(showgrid=True, gridcolor='lightgrey'),
    yaxis=dict(showgrid=True, gridcolor='lightgrey'),
    template="plotly_white",
    hovermode='x unified'
)

fig.show()

"""After 1 year, the accumulated value is around ₹64,000 and by 5 years, it grows to over ₹1,300,000. The long-term benefit is evident, with the investment growing to nearly ₹7,290,000 over 10 years, which emphasises the value of consistent investing and compounding over time for long-term investors.

# Summary

## Project Report: Mutual Fund Plan with Python
## ME_id : ACTIVITY_PROJECT_DEMO_MUTUAL_FUND_PLAN_PYTHON
### Headline
Analyze Nifty 50 closing prices to create a mutual fund plan based on high ROI and low risk.
### Image

### Overview
- Objective - To create a mutual fund investment plan based on high ROI and low risk using Python.
- Data Cleaning - Checked for missing values in the dataset.
- Data Analysis - Calculated volatility, growth rate, and ROI for each company, then identified companies with high ROI and low risk.
- Insights - Companies with high ROI and low volatility are suitable for long-term, stable growth.
- Deliverable - A mutual fund plan recommending investment ratios for selected companies and a projection of expected returns over time.

## Milestone 0:
### Extended Overview
- Data Collection & Cleaning - Loaded Nifty 50 closing prices from a CSV file and converted the 'Date' column to datetime format. Checked for and confirmed no missing values in the dataset.
- Data Analysis - Calculated the standard deviation of closing prices as a measure of volatility, the percentage change as a measure of growth rate, and the overall return on investment (ROI) for each company.
- Data Visualization - Visualized stock price trends over time using line plots. Compared the risk and expected ROI of the selected mutual fund companies against high growth rate companies using bar plots.
- Trend Analysis - Observed that stock prices fluctuate over time, with some companies showing higher volatility than others. High growth rate companies tend to have higher volatility, while the selected mutual fund companies exhibit lower volatility and moderate returns, suitable for long-term, stable growth.
- Summary - Developed a mutual fund plan by selecting companies with ROI above the median and volatility below the median. Calculated investment ratios based on inverse volatility, giving higher weight to less volatile companies. Projected the accumulated value of monthly investments with annual increases over various time periods, demonstrating the power of compounding for long-term investors.

So, this is how a mutual fund plan is designed by investment companies for long-term investors. Mutual funds are investment plans that pool money from multiple investors to purchase a diversified portfolio of stocks, bonds, and other securities, managed by professional fund managers.
"""